eureka:
  client:
    register-with-eureka: false       #Declaring its not a client but server
    fetch-registry: false
    
    
server:
 port: 8761
 
 spring:
   application:
      name : AMAZON-SERVER