eureka:
  client:
    register-with-eureka: true       #Declaring its not a client but server
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   # This will help Eureka server to register this service as client
  instance:
     hostname: localhost  
    
server:
 port: 9091
 
 spring:
   application:
      name : SHOPPING-SERVICE  #This name we will be able to see in the Eureka Server